### ISSUE TITLE
Card Description into OF Task description 

### ISSUE THREAD

**Issue by eyesuk** [vesan/omnifocus-trello#7]
Is there a way that we can extract the card description and place it in the task description within omnifocus?  Currently the Card link is placed in the OF task description.

**Comment by vesan** [comment]
Yes, that is in fact possible. I released version 1.2.0 a couple of minutes ago and it places the Trello card description to the todo's description.

Thanks for the idea!

**Comment by eyesuk** [comment]
Thanks for the Update!  I appreciate it.  it appears that the new version was installed, however when I run sudo of sync, it apears to be the old version since the OF tasks does not Include the Trello Card description.

Fetching: omnifocus-trello-1.2.0.gem (100%)
Successfully installed omnifocus-trello-1.2.0
Parsing documentation for omnifocus-trello-1.2.0
Installing ri documentation for omnifocus-trello-1.2.0
1 gem installed

Thanks for your help, it is really appreciate it

**Comment by vesan** [comment]
Oh yeah, it's probably only for new cards. So because your cards are already imported to OmniFocus, it doesn't re-sync them. This is probably because you might have edited the description yourself and omnifocus gem doesn't want to override your custom description.

It would be great if you could add a new card with description, mark yourself to the card and then sync and check that the description came fine to OmniFocus. If it doesn't work for new cards, then it's definitely a bug. It worked fine for me though.

**Comment by eyesuk** [comment]
you are awesome! thank you very much! can I send a donation your way for your time and effort?

**Comment by vesan** [comment]
Oh yeah, you commented also on my blog :-)

You can donate the money to your favorite charity or get something nice to somebody you love. Your nice words are good reward for my efforts.

**Comment by eyesuk** [comment]
Done Deal! thank you sir....
